### ISSUE TITLE
Implement the form stepper from our design

### ISSUE THREAD

**Issue by CoreyAR** [MusicCityLegalHackers/power-of-attorney-challenge#10]
See the [Zeplin Design](https://app.zeplin.io/project/5adb2c9f32cffe0d11d2de86/screen/5adb2d15f8777315bf81a97a).  Here's a screenshot of the first step as an example:

<img width="1046" alt="First step of the form, with form stepper" src="https://user-images.githubusercontent.com/4812055/39086481-abc6a728-4557-11e8-8a27-83aab97a15c4.png">

If there's a Grommet or React form stepper, prefer using those tools.

**Comment by ebmshenfield** [comment]
April Petry has worked up a design for the stepper - will upload the design to Invision and link tomorrow.
