### ISSUE TITLE
Numbering Off

### ISSUE THREAD

**Issue by kevinahuber** [MusicCityLegalHackers/power-of-attorney-challenge#28]
Looks like the father & mother is two steps in the actual form, but only one step in the breadcrumbs, causing it to be one step off. What is the desired behavior for this?

![image](https://user-images.githubusercontent.com/6272414/39612170-9e964552-4f22-11e8-97ac-1342e8721f60.png)

**Comment by mshenfield** [comment]
@kevinahuber just fixed
