### ISSUE TITLE
Implement the form disclaimer modal from the design

### ISSUE THREAD

**Issue by mshenfield** [MusicCityLegalHackers/power-of-attorney-challenge#7]
The modal should be displayed any time a user navigates to the `/form` page.

Here's a screenshot of the design:

<img width="1089" alt="screen shot 2018-04-21 at 11 35 13 am" src="https://user-images.githubusercontent.com/4812055/39086510-1401de84-4558-11e8-8dcb-d04374511ec4.png">

the full design can be found on [Zeplin](https://app.zeplin.io/project/5adb2c9f32cffe0d11d2de86/screen/5adb2d07de066c8633169914).

**Comment by combinatorist** [comment]
See WIP: https://github.com/MusicCityLegalHackers/power-of-attorney-challenge/tree/feature/add-disclaimer-modal

**Comment by ebmshenfield** [comment]
April Petry has worked up a design for the modal - will upload the design to Invision and link tomorrow.

**Comment by mshenfield** [comment]
Noting that the WIP progress branch (https://github.com/MusicCityLegalHackers/power-of-attorney-challenge/tree/feature/add-disclaimer-modal) doesn't reflect  the new design, but might still useful as a starting point for integrating with the form view.
